"""temp vars table

Revision ID: 51eb238a19f4
Revises: 8a92dd29b630
Create Date: 2025-04-17 10:48:40.692106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '51eb238a19f4'
down_revision = '8a92dd29b630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_temp_vars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'key', name='_workflow_key_uc')
    )
    with op.batch_alter_table('workflow_temp_vars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_temp_vars_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_temp_vars_workflow_id'), ['workflow_id'], unique=False)

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('temp_vars')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_vars', sqlite.JSON(), nullable=False))

    with op.batch_alter_table('workflow_temp_vars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_temp_vars_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_temp_vars_key'))

    op.drop_table('workflow_temp_vars')
    # ### end Alembic commands ###
