"""workflow vars json

Revision ID: 5302c307d7eb
Revises: bc77cf1acb35
Create Date: 2025-04-17 12:46:51.586724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5302c307d7eb'
down_revision = 'bc77cf1acb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_temp_vars', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.BLOB(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_temp_vars', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.JSON(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
