"""add indices

Revision ID: 567ea91c35be
Revises: 778692bce078
Create Date: 2025-04-16 11:31:30.912727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567ea91c35be'
down_revision = '778692bce078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_context_assets', schema=None) as batch_op:
        batch_op.create_index('idx_card_context_asset_card_id_version', ['card_id', 'card_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_context_assets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_context_assets_tag'), ['tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_context_assets_type'), ['type'], unique=False)

    with op.batch_alter_table('card_file_assets', schema=None) as batch_op:
        batch_op.create_index('idx_card_file_asset_card_id_version', ['card_id', 'card_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_file_assets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_file_assets_tag'), ['tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_file_assets_type'), ['type'], unique=False)

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_modification_date'), ['modification_date'], unique=False)

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chats_modification_time'), ['modification_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chats_modification_time'))

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_modification_date'))
        batch_op.drop_index(batch_op.f('ix_cards_creation_date'))

    with op.batch_alter_table('card_file_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_file_assets_type'))
        batch_op.drop_index(batch_op.f('ix_card_file_assets_tag'))
        batch_op.drop_index(batch_op.f('ix_card_file_assets_name'))
        batch_op.drop_index('idx_card_file_asset_card_id_version')

    with op.batch_alter_table('card_context_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_context_assets_type'))
        batch_op.drop_index(batch_op.f('ix_card_context_assets_tag'))
        batch_op.drop_index(batch_op.f('ix_card_context_assets_name'))
        batch_op.drop_index('idx_card_context_asset_card_id_version')

    # ### end Alembic commands ###
