"""add vars to messages

Revision ID: 778692bce078
Revises: e16c317122cc
Create Date: 2025-04-16 10:35:35.478065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778692bce078'
down_revision = 'e16c317122cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vars', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('vars')

    # ### end Alembic commands ###
