"""api key

Revision ID: 8a92dd29b630
Revises: 567ea91c35be
Create Date: 2025-04-16 14:25:37.727965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a92dd29b630'
down_revision = '567ea91c35be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apis_api_type'), ['api_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_apis_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_apis_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_apis_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apis_source'))
        batch_op.drop_index(batch_op.f('ix_apis_name'))
        batch_op.drop_index(batch_op.f('ix_apis_model'))
        batch_op.drop_index(batch_op.f('ix_apis_api_type'))

    # ### end Alembic commands ###
