"""change message_vars

Revision ID: bc77cf1acb35
Revises: e6624a43d5e0
Create Date: 2025-04-17 12:42:54.159574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc77cf1acb35'
down_revision = 'e6624a43d5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_vars', schema=None) as batch_op:
        batch_op.drop_index('ix_message_vars_key')
        batch_op.drop_constraint('uq_message_var_key', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_vars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.create_unique_constraint('uq_message_var_key', ['message_id', 'key'])
        batch_op.create_index('ix_message_vars_key', ['key'], unique=False)

    # ### end Alembic commands ###
