"""init

Revision ID: e16c317122cc
Revises: 
Create Date: 2025-04-15 11:24:00.412376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16c317122cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('api_url', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('creator', sa.String(length=100), nullable=False),
    sa.Column('creator_note', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('modification_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_table('chats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('modification_time', sa.DateTime(), nullable=False),
    sa.Column('head', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('graph', sa.JSON(), nullable=False),
    sa.Column('temp_vars', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_chat_association',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'chat_id')
    )
    op.create_table('card_context_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ext', sa.String(length=10), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('card_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['card_id', 'card_version'], ['cards.id', 'cards.version'], name='card_context_asset_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_file_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ext', sa.String(length=10), nullable=False),
    sa.Column('uri', sa.String(length=255), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('card_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['card_id', 'card_version'], ['cards.id', 'cards.version'], name='card_file_asset_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('modification_time', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=True),
    sa.Column('card_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['card_id', 'card_version'], ['cards.id', 'cards.version'], name='message_card_fk'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_parent_id'), ['parent_id'], unique=False)

    op.create_table('nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('node_subtype', sa.String(), nullable=False),
    sa.Column('on', sa.Boolean(), nullable=False),
    sa.Column('interface', sa.JSON(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('handler', sa.Text(), nullable=True),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('static_input', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_card_association',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'card_id')
    )
    op.create_table('agent_variables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['target'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    op.drop_table('agent_variables')
    op.drop_table('agent_card_association')
    op.drop_table('nodes')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_parent_id'))
        batch_op.drop_index(batch_op.f('ix_messages_chat_id'))

    op.drop_table('messages')
    op.drop_table('card_file_assets')
    op.drop_table('card_context_assets')
    op.drop_table('card_chat_association')
    op.drop_table('agents')
    op.drop_table('workflows')
    op.drop_table('chats')
    op.drop_table('cards')
    op.drop_table('apis')
    # ### end Alembic commands ###
