"""Add MessageVar table and update Message model

Revision ID: e6624a43d5e0
Revises: 51eb238a19f4
Create Date: 2025-04-17 12:38:11.194279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e6624a43d5e0'
down_revision = '51eb238a19f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_vars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'key', name='uq_message_var_key')
    )
    with op.batch_alter_table('message_vars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_vars_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_vars_message_id'), ['message_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('vars')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vars', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('message_vars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_vars_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_vars_key'))

    op.drop_table('message_vars')
    # ### end Alembic commands ###
